txtDisplay = Entry(f2, font=('arial',20, 'bold'), textvariable=text_Input, bd=5, insertwidth=9, justify='right')
txtDisplay.grid(columnspan=4)
btn7=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="7",command=lambda:btnClick(7)).grid(row=1, column=0)
btn8=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="8",command=lambda:btnClick(8)).grid(row=1, column=1)
btn9=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="9",command=lambda:btnClick(9)).grid(row=1, column=2)
btnplus=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="+",command=lambda:btnClick("+")).grid(row=1, column=3
k=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="4",command=lambda:btnClick(4)).grid(row=3, column=0)
btn5=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="5",command=lambda:btnClick(5)).grid(row=3, column=1)
btn6=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="6",command=lambda:btnClick(6)).grid(row=3, column=2)
btnSub=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="-",command=lambda:btnClick("-")).grid(row=3, column=3)
btn1=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="1",command=lambda:btnClick(1)).grid(row=4, column=0)
btn2=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="2",command=lambda:btnClick(2)).grid(row=4, column=1)
btn3=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="3",command=lambda:btnClick(3)).grid(row=4, column=2)
btnMult=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="*",command=lambda:btnClick("*")).grid(row=4, column=3
btn0=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="0",command=lambda:btnClick(0)).grid(row=5, column=0)
btnClear=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="C",command=btnClearDisplay).grid(row=5, column=1)
btnEquals=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="=",command=btnEqualsInput).grid(row=5, column=2)
btnDiv=Button(f2, padx=16, pady=16, bd=8, fg="black", font=('arial',20,'bold'),text="/",command=lambda:btnClick("/")).grid(row=5, column=3)
lblRef=Label(f1aa, font=('arial',16,'bold'), text="Sales Reference", bd=16, justify='left')
lblRef.grid(row=0,column=0)
txtRef=Entry(f1aa, font=('arial',16,'bold'), textvariable=PaymentRef, bd=5, insertwidth=2, justify='left')
txtRef.grid(row=0, column=1)
lblpizza=Label(f1aa, font=('arial',16,'bold'), text="Pizza", bd=16, anchor='w')
lblpizza.grid(row=1,column=0)
txtpizza=Entry(f1aa, font=('arial',16,'bold'), textvariable=pizza, bd=5, insertwidth=2, justify='left')
txtpizza.grid(row=1, column=1)
lblburger=Label(f1aa, font=('arial',16,'bold'), text="Burger", bd=16, anchor='w')
lblburger.grid(row=2,column=0)
txtburger=Entry(f1aa, font=('arial',16,'bold'), textvariable=burger, bd=5, insertwidth=2, justify='left')
txtburger.grid(row=2, column=1)
lbldrink=Label(f1aa, font=('arial',16,'bold'), text="Cold Drinks", bd=16, anchor='w')
lbldrink.grid(row=3,column=0)
txtdrink=Entry(f1aa, font=('arial',16,'bold'), textvariable=drink, bd=5, insertwidth=2, justify='left')
txtdrink.grid(row=3, column=1)
lblHomeDelivery=Label(f1aa, font=('arial',16,'bold'), text="Home Delivery", bd=16, anchor='w')
lblHomeDelivery.grid(row=4,column=0)
txtHomeDelivery=Entry(f1aa, font=('arial',16,'bold'), textvariable=HomeDelivery, bd=5, insertwidth=2, justify='left')
txtHomeDelivery.grid(row=4, column=1)
lblDateofOrder=Label(f1ab, font=('arial',16,'bold'), text="Date of Order", bd=16, anchor='w')
lblDateofOrder.grid(row=0,column=0)
txtDateofOrder=Entry(f1ab, font=('arial',16,'bold'), textvariable=DateofOrder, bd=5, insertwidth=2, justify='left')
txtDateofOrder.grid(row=0, column=1)
lblCostofpizza=Label(f1ab, font=('arial',16,'bold'), text="Cost of Pizza", bd=16, anchor='w')
lblCostofpizza.grid(row=1,column=0)
txtCostofpizza=Entry(f1ab, font=('arial',16,'bold'), textvariable=Costofpizza, bd=5, insertwidth=2, justify='left')
txtCostofpizza.grid(row=1, column=1)
lblCostofburger=Label(f1ab, font=('arial',16,'bold'), text="Cost of Burger", bd=16, anchor='w')
lblCostofburger.grid(row=2,column=0)
